apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: orlando.capoeiraraiz@gmail.com  # Replace with your email
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          cloudflare:
            email: orlando.capoeiraraiz@gmail.com  # Leave blank if using API token
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token