repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: jetstack
    url: https://charts.jetstack.io
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: external-dns
    url: https://kubernetes-sigs.github.io/external-dns/
  - name: external-secrets
    url: https://charts.external-secrets.io  

releases:
  - name: nginx-ingress
    namespace: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    version: 4.10.1
    createNamespace: true
    values:
      - values/nginx-ingress.yaml

  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: v1.18.0
    createNamespace: true
    values:
      - values/cert-manager.yaml

  - name: external-dns
    namespace: external-dns
    chart: external-dns/external-dns
    version: 1.16.1
    createNamespace: true
    values:
      - values/external-dns.yaml
  
  - name: external-secrets
    namespace: external-secrets
    chart: external-secrets/external-secrets
    version: v0.18.2
    createNamespace: true
    values:
      - values/external-secrets.yaml  
