installCRDs: true
replicaCount: 2

image:
  repository: oci.external-secrets.io/external-secrets/external-secrets
  tag: "v0.9.10"
  pullPolicy: IfNotPresent

leaderElect: true
controllerClass: "external-secrets-controller"

scopedNamespace: "external-secrets"
scopedRBAC: true

processClusterStore: true
processClusterExternalSecret: true

serviceAccount:
  create: true

rbac:
  create: true

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

metrics:
  listen:
    port: 8080

serviceMonitor:
  enabled: true
  interval: 30s
