# apiVersion: external-secrets.io/v1beta1
# kind: SecretStore
# metadata:
#   name: openbao-store
#   namespace: external-secrets
# spec:
#   provider:
#     vault:
#       server: https://openbao.external:8200
#       path: kv
#       version: v2
#       auth:
#         kubernetes:
#           mountPath: kubernetes
#           role: external-secrets
#           serviceAccountRef:
#             name: external-secrets
